name: Cargo Publish

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  publish:
    name: Publish to crates.io
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: Remove unused programs
        run: |
          rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL || true
      - name: Install linux dependencies
        if: runner.os == 'Linux'
        uses: ./.github/actions/linux-system-deps
      - name: Install the rust toolchain
        uses: dtolnay/rust-toolchain@1.94
      - run: cargo publish --features skia-engine --workspace --exclude "examples" --exclude "website" --exclude "freya-devtools-app"
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
