name: Release Drafter

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize]

permissions: {}

jobs:
  update_release_draft:
    permissions:
      contents: write
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
